FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD egit.jar /opt/egit/
EXPOSE 8080
WORKDIR /opt/egit/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "egit.jar"]
